services:
  - type: web
    name: projet-maktabislamiya
    env: php
    plan: free
    branch: main
    buildCommand: |
      composer install
      php artisan config:clear
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:i8M1I3SajaVPd9Y+p+JjiNp9QiVR7O50CAX2AxV+ib8=
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d18r0femcj7s73abnjkg-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: maktabislam
      - key: DB_USERNAME
        value: maktabislam_user
      - key: DB_PASSWORD
        value: xrgRhWfpYrhcNpP4bNxNAWosKKz9atjP
