services:
  - type: web
    name: library-project
    env: php
    branch: main
    buildCommand: |
      composer install
      npm ci
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    autoDeploy: true
