services:
  - type: web
    name: library-project
    runtime: docker
    repo: https://github.com/Dadowatt/library-project
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d128sijuibrs73evpg8g-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: maktabaislamiya
      - key: DB_USERNAME
        value: watt123
      - key: DB_PASSWORD
        value: KCK30b62wE9Vh5tr7xTJ8Xa4IGc56TXj
